name: New Release

on:
  repository_dispatch:
    types: [new_release]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ github.event.client_payload.ref }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.client_payload.ref }}
          files: |
            install.sh
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}